#ifndef CHRONO_SYNCHRONO_DDS_IDL_SYNDDSMESSAGE_PUBSUBTYPES_WRAPPER_H
#define CHRONO_SYNCHRONO_DDS_IDL_SYNDDSMESSAGE_PUBSUBTYPES_WRAPPER_H

#include "chrono_synchrono/SynConfig.h"

#if defined(CHRONO_SYNCHRONO_FASTDDS_API) && CHRONO_SYNCHRONO_FASTDDS_API >= 3
    #include "fastdds3/SynDDSMessagePubSubTypes.hpp"
#else
    #include "fastdds2/SynDDSMessagePubSubTypes.h"
#endif

#endif  // CHRONO_SYNCHRONO_DDS_IDL_SYNDDSMESSAGE_PUBSUBTYPES_WRAPPER_H
